name: gvl_comments
description: Add a comments section to any Flutter app (UI + managed backend). No Firebase/Supabase setupâ€”just an install key.
version: 0.9.7
homepage: https://goodvibeslab.cloud
repository: https://github.com/GoodVibesLab/gvl_comments
issue_tracker: https://github.com/GoodVibesLab/gvl_comments/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.6.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  meta: ^1.16.0
  intl: ^0.20.2
  crypto: ^3.0.7

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  
  plugin:
    platforms:
      android:
        package: com.goodvibeslab.gvl_comments
        pluginClass: GvlCommentsPlugin
      ios:
        pluginClass: GvlCommentsPlugin

  assets:
    - assets/gvl_cloud_logo.png

